/********************************** (C) COPYRIGHT *******************************
 * File Name          : main.c
 * Author             : WCH
 * Version            : V1.0.0
 * Date               : 2025/06/06
 * Description        : Main program body.
 *********************************************************************************
 * Copyright (c) 2021 Nanjing Qinheng Microelectronics Co., Ltd.
 * Attention: This software (modified or not) and binary are used for
 * microcontroller manufactured by Nanjing Qinheng Microelectronics.
 *******************************************************************************/

#include "debug.h"
#include "cart.h"
#include "psram.h"
#include "cli.h"
#include "scc.h"
#include "tone.h"
#include "loader.h"
#include "usb_disk.h"
#include "usb_tests.h"
#include <string.h>

/* Embedded cart ROM image (mapper test). Generated by tools/rom2c.py
 * from MSXSoftware/MapperTest/maptest.bin; see maptest_rom.c. 32 KiB,
 * flash-resident. */
extern const uint8_t maptest_rom[];
extern const uint32_t maptest_rom_len;

/* The embedded test ROM is still linked (psram.c references
 * maptest_rom for its size check) but is NO LONGER auto-loaded at boot:
 * Boot_LoadEmbeddedRom() is disabled so the MSX drops to BASIC unless
 * a cart image is uploaded via XLOAD. To re-enable booting the test,
 * mirror maptest_rom[] into PSRAM and install ROM32k here. */
__attribute__ ((unused)) static void Boot_LoadEmbeddedRom (void) {
    if (maptest_rom_len >= PSRAM_CART_SIZE) {
        printf ("Cart image: PSRAM @ 0x%08x (placeholder; upload via XLOAD)\r\n",
                (unsigned)PSRAM_CART_BASE);
        return;
    }
    /* Copy maptest_rom -> PSRAM at offset 0. PSRAM_Init() already
     * mirrors the image; we only need to do it again if PSRAM_Init
     * failed and we're falling back to PSRAM (which should never
     * happen here since the caller checks the status first). */
    if (PSRAM_GetRomMirrorBase() != 0U) {
        memcpy ((void *)PSRAM_CART_BASE, maptest_rom, maptest_rom_len);
        printf ("Cart image: PSRAM @ 0x%08x (32 KiB, embedded mapper test ROM)\r\n",
                (unsigned)PSRAM_CART_BASE);
    } else {
        printf ("Cart image: PSRAM not initialised; embedded ROM NOT mirrored\r\n");
    }
}

int main (void) {

    /* Heartbeat: toggle the LED in a tight loop so we can confirm
     * main() is reached even if USART is dead. PA0 = LEDFLASH. */
    {
        RCC_PB2PeriphClockCmd(RCC_PB2Periph_GPIOA, ENABLE);
        GPIOA->CFGLR &= ~(0xFu << 0);
        GPIOA->CFGLR |=  (0x3u << 0);
        for (volatile int i = 0; i < 200000; i++) {
            GPIOA->OUTDR ^= (1u << 0);
        }
    }

    /* Run clock diagnostics BEFORE SystemCoreClockUpdate so we can see
     * the raw RCC state. USART_Printf_Init uses SystemCoreClock for
     * baud calc, but at this point we're still on HSI 20 MHz so the
     * baud will be correct (SystemCoreClock default = HSI_VALUE). */
    // ClockTree_Diag();

    SystemCoreClockUpdate();
    Delay_Init();

    SystemCoreClockUpdate();
    Delay_Init();

    /* Bring up USART BEFORE any driver whose init breadcrumbs print
     * (SCC_Init's SCC_DEBUG prints in particular). If USART_Printf_Init
     * runs AFTER SCC_Init, those prints either drop silently (USART
     * TX path uninitialised) OR hang in the printf spinwait on TXE
     * that never fires, stopping boot before "SystemClk:" is ever
     * printed. USART_Printf_Init reads SystemCoreClock for the baud
     * divisor, so SystemCoreClockUpdate() must run before it (done
     * above). PWR_VDD18LevelConfig is the only post-USART concern
     * and is unrelated to print output. */
    USART_Printf_Init (921600);
    PWR_VDD18LevelConfig(PWR_VDD18_Level1);

    /* Hold the MSX in reset IMMEDIATELY so its BIOS waits while the
     * firmware finishes booting. The cart must be fully armed before
     * the MSX sees its first rising edge on ~RESET, otherwise the
     * BIOS probes 0x4000 with no slot active and falls through to
     * BASIC. Cart_AssertMSXReset_Begin drives PE4 low; we keep it low
     * through the rest of boot and only release at the end. */
    Cart_AssertMSXReset_Begin ();
    Init_Cart ();
    SCC_Init ();
    int loader_rc = Cart_SetMapper (CART_MAP_FLASH);

#if TONE_DEFAULT_ON
    /* Bring up the DAC tone generator (audio-path self-test). Drives
     * PA4 with a sine/triangle/square/DC waveform via TIM4 + DMA +
     * DAC1, independent of the SCC emulator. The CLI `TONE` command
     * can hot-swap waveform/freq later. Default sample_rate = 44100
     * (legacy SCC value) → audio_freq = 44100 / 256 ≈ 172 Hz, well
     * inside TIM4's 16-bit period register and clearly audible on
     * earphones.
     * TONE_DEFAULT_ON is 0 by default so boot leaves the SCC audio
     * path active for cart games; flip to 1 (or use `TONE START`
     * from the CLI) for self-test. */
    Tone_Init (44100U, TONE_WAVE_SINE);
#endif

    printf ("SystemClk:%d\r\n", SystemCoreClock);
    printf ("ChipID:%08x\r\n", DBGMCU_GetCHIPID());

    /* Bring up PSRAM after the flash selector is already armed. It is
     * only needed later when the user loads a cartridge image. */
    uint8_t psram_status = PSRAM_Init();
    if (psram_status == PSRAM_OK) {
        printf ("PSRAM: OK, cart image @ 0x%08x (%u bytes)\r\n",
                (unsigned)PSRAM_CART_BASE, (unsigned)PSRAM_CART_SIZE);
        printf ("Cart: game base = %u MiB (image served at PSRAM+0x%08x,\r\n"
                "      %u bytes remaining - build knob GAME_BASE_MB=%u)\r\n",
                (unsigned)CART_GAME_BASE_MB,
                (unsigned)Cart_GetGameBase(),
                (unsigned)(PSRAM_CART_SIZE - Cart_GetGameBase()),
                (unsigned)CART_GAME_BASE_MB);
    } else {
        printf ("PSRAM: init FAILED status=0x%02x\r\n",
                (unsigned)psram_status);
    }

    /* Boot straight into the ROM selector from flash. The ROM32k path
     * serves selector_rom[] for 0x4000..0xBFFF and also exposes the
     * mailbox window used by the MSX-side loader. */
    if (loader_rc == 0) {
        printf ("Cart: ROM32k mapper installed "
                "(MSX boots into the ROM selector)\r\n");
    } else {
        printf ("Cart: ROM32k install FAILED\r\n");
    }

    /* USBHS host init. Powers up the controller so it's ready. */
    USB_Initialization ();
    printf ("USBHS: host controller ready\r\n");

    /* CLI: USART1 command interface.  Commands are dispatched from the
     * main loop (CLI_Service below), never from the IRQ. */
    CLI_Init ();

    /* Firmware is up and the flash selector is armed. Now release the
     * MSX from reset so the BIOS can probe 0x4000 and find 'AB'. */
    printf ("loader mbox addr=0x%08x status=0x%02x\r\n",
            (unsigned)&g_loader_mbox, (unsigned)g_loader_mbox.status);
    Cart_AssertMSXReset_End ();

    printf ("\r\n=== boot complete ===\r\n");

    /* Idle loop: service CLI commands + the ROM-loader mailbox, sleep
     * between interrupts.  Loader_Service drains any command the MSX
     * posted through the cart mailbox (dir listing, file load, mapper
     * switch, reset). */
    for (;;) {
        CLI_Service ();
        Loader_Service ();
#if SCC_DEBUG
        /* Main-loop DAC probe: read Dual_DAC_Value once per boot + then
         * every ~5s. The TIM4_IRQHandler is producing ~44100 samples/s
         * but logging them all floods the USART; once per ~5s is
         * enough to confirm the value is updating (will tick up / down
         * as the SCC sample pump runs) AND that the DMA target RAM
         * is non-zero (proves DMA path is wired). Uses the SysTick or
         * a free counter - we don't have one readily, so just print
         * on every loop pass and let the user throttle via the toggle
         * if it's too noisy. */
        {
            static uint32_t tick = 0;
            static uint32_t last_dac = 0xFFFFFFFFU;
            const uint32_t cur = SCC_GetDualDacValue ();
            if (++tick == 1U || cur != last_dac) {
                /* First pass + every change. If `cur` stays pinned at
                 * 0x800 (mid-scale default) the SCC never wrote a
                 * non-zero sample - either no cart writes reached the
                 * IRQ, or emu2212 is stuck inactive (check
                 * `s_scc->active` via the SCC CLI diagnostic). */
                printf ("DAC: Dual_DAC_Value=0x%03x 0x800=mid\r\n",
                        (unsigned)(cur & 0xFFFU));
                last_dac = cur;
                if (tick == 1U) {
                    /* First pass: note it so the rate slows back to
                     * every-change thereafter. */
                }
                if (tick >= 1000U) tick = 0;  /* safety wrap */
            }
        }
#endif
        __asm__ volatile ("wfi");
    }
}