/********************************** (C) COPYRIGHT *******************************
 * File Name          : main.c
 * Author             : WCH
 * Version            : V1.0.0
 * Date               : 2025/06/06
 * Description        : Main program body.
 *********************************************************************************
 * Copyright (c) 2021 Nanjing Qinheng Microelectronics Co., Ltd.
 * Attention: This software (modified or not) and binary are used for
 * microcontroller manufactured by Nanjing Qinheng Microelectronics.
 *******************************************************************************/

#include "debug.h"
#include "cart.h"
#include "psram.h"
#include "cli.h"
#include "usb_disk.h"
#include <string.h>

/* Embedded cart ROM image (psramdiag v2). Generated by tools/rom2c.py
 * from MSXSoftware/HelloWorld/psramdiag.bin; see hello_rom.c. 32 KiB,
 * flash-resident. */
extern const uint8_t hello_rom[];
extern const uint32_t hello_rom_len;

/* The embedded psramdiag ROM is still linked (psram.c references
 * hello_rom for its size check) but is NO LONGER auto-loaded at boot:
 * Boot_LoadEmbeddedRom() is disabled so the MSX drops to BASIC unless
 * a cart image is uploaded via XLOAD. To re-enable booting the
 * diagnostic, mirror hello_rom[] into PSRAM and install ROM32k here. */
__attribute__ ((unused)) static void Boot_LoadEmbeddedRom (void) {
    if (hello_rom_len >= PSRAM_CART_SIZE) {
        printf ("Cart image: PSRAM @ 0x%08x (placeholder; upload via XLOAD)\r\n",
                (unsigned)PSRAM_CART_BASE);
        return;
    }
    /* Copy hello_rom -> PSRAM at offset 0. PSRAM_Init() already
     * mirrors the image; we only need to do it again if PSRAM_Init
     * failed and we're falling back to PSRAM (which should never
     * happen here since the caller checks the status first). */
    if (PSRAM_GetRomMirrorBase() != 0U) {
        memcpy ((void *)PSRAM_CART_BASE, hello_rom, hello_rom_len);
        printf ("Cart image: PSRAM @ 0x%08x (32 KiB, embedded psramdiag ROM)\r\n",
                (unsigned)PSRAM_CART_BASE);
    } else {
        printf ("Cart image: PSRAM not initialised; embedded ROM NOT mirrored\r\n");
    }
}

/* HSE / clock-tree diagnostics. Run BEFORE USART_Printf_Init, while we're
 * still clocked by HSI (USART1 baud uses SysCoreClock; if HSE failed we
 * can't trust printf anyway, so this is informational only — the real
 * test is the SystemClk line printed after SystemCoreClockUpdate).
 *
 * Bit map printed:
 *   CTLR   = RCC->CTLR  (HSEON bit, HSERDY flag, PLL flags)
 *   CFGR0  = RCC->CFGR0 (SW[1:0] + SWS[1:0] = which clock is sysclk)
 *   CFGR2  = RCC->CFGR2 (SYSPLLSRC + SYSPLLDIV selection)
 *   INTR   = RCC->INTR  (HSERDYF / CSSD / PLL ready flags)
 *   HSE_VALUE expected  = the constant the build was compiled with
 *   ChipID = DBGMCU->IDR (CH32V407VET6 = 0x467304x? - sanity vs board)
 */
static void ClockTree_Diag (void) {
    uint32_t ctlr = RCC->CTLR;
    uint32_t cfgr0 = RCC->CFGR0;
    uint32_t cfgr2 = RCC->CFGR2;
    uint32_t intr = RCC->INTR;
    uint32_t sw = cfgr0 & 0x03u;
    uint32_t sws = cfgr0 & 0x0Cu;
    printf ("CLK DIAG: CTLR=%08x CFGR0=%08x CFGR2=%08x INTR=%08x\r\n",
            (unsigned)ctlr, (unsigned)cfgr0, (unsigned)cfgr2, (unsigned)intr);
    printf ("  HSEON=%lu HSERDY=%lu PLLON=%lu PLLRDY=%lu HSEBYP=%lu CSSON=%lu\r\n",
            (unsigned)((ctlr >> 16) & 1u),
            (unsigned)((ctlr >> 17) & 1u),
            (unsigned)((ctlr >> 24) & 1u),
            (unsigned)((ctlr >> 25) & 1u),
            (unsigned)((ctlr >> 18) & 1u),
            (unsigned)((ctlr >> 19) & 1u));
    printf ("  SW=%lu SWS=%lu  (0=HSI 1=HSE 2=PLL)\r\n",
            (unsigned)sw, (unsigned)(sws >> 2));
    printf ("  HSE_VALUE(build)=%lu Hz  ChipID=%08x\r\n",
            (unsigned)HSE_VALUE, (unsigned)DBGMCU_GetCHIPID());
    /* If HSE failed to start, fail loud so the boot log tells us */
    if (((ctlr >> 16) & 1u) && !((ctlr >> 17) & 1u)) {
        printf ("  *** HSE IS ON BUT NOT READY (crystal/loadcaps/board fault?) ***\r\n");
    }
    /* If SWS says HSI while SW is set to PLL/HSE, the SetSysClock else{}
     * branch silently fell through and the chip is running on HSI. */
    if (((sws >> 2) == 0u) && (sw != 0u)) {
        printf ("  *** SYSCLK=HSI despite SW!=0 - clock-switch else{} fell through ***\r\n");
    }
}

int main (void) {

    /* Run clock diagnostics BEFORE SystemCoreClockUpdate so we can see
     * the raw RCC state. USART_Printf_Init uses SystemCoreClock for
     * baud calc, but at this point we're still on HSI 20 MHz so the
     * baud will be correct (SystemCoreClock default = HSI_VALUE). */
    // ClockTree_Diag();

    SystemCoreClockUpdate();
    Delay_Init();
    USART_Printf_Init (921600);
    PWR_VDD18LevelConfig(PWR_VDD18_Level1);
    printf ("SystemClk:%d\r\n", SystemCoreClock);
    printf ("ChipID:%08x\r\n", DBGMCU_GetCHIPID());

    /* Install EXTI0 + default NONE mapper. The bus stays tri-stated
     * until a mapper is selected - safe because PSRAM is not yet
     * initialised. PSRAM_Init() must complete before any non-NONE
     * mapper is accepted (see Cart_SetMapper). */
    Init_Cart();

    /* CLI early: lets the host see diagnostic output while PSRAM is
     * being brought up, and lets us report PSRAM_Init errors over
     * the serial line. */
    CLI_Init();

    /* USBHS host init. The enumeration runs only when the user types
     * the `USB` CLI command (see cli.c); this just powers up the
     * controller so it's ready. */
    USB_Initialization ();
    printf ("USBHS: host controller ready (enumeration deferred to `USB` cmd)\r\n");

    /* Bring up PSRAM. After this, the 64 Mbit / 8 MiB external memory
     * is accessible at 0x80000000..0x80800000 and is usable as the
     * cart image window. */
    uint8_t psram_status = PSRAM_Init();
    if (psram_status == PSRAM_OK) {
        printf ("PSRAM: OK, cart image @ 0x%08x (%u bytes)\r\n",
                (unsigned)PSRAM_CART_BASE, (unsigned)PSRAM_CART_SIZE);
        /* No embedded ROM is loaded: PSRAM_Init fills the cart window
         * with 0xFF (open bus). With mapper NONE the bus stays tri-
         * stated and the MSX boots straight into BASIC. Upload a cart
         * with XLOAD, then switch mappers via the MAP command. */
        printf ("Cart mapper: NONE (MSX will drop to BASIC; "
                "XLOAD + MAP to run a cart)\r\n");
    } else {
        printf ("PSRAM: init FAILED status=0x%02x\r\n", (unsigned)psram_status);
        if (psram_status & PSRAM_ERR_HCLK_TOO_HIGH)
            printf ("  HCLK %u MHz above 200 MHz limit (core clock = HCLK "
                    "on this chip, no independent PSRAM divider)\r\n",
                    (unsigned)(SystemCoreClock / 1000000U));
        if (psram_status & PSRAM_ERR_CLOCK)
            printf ("  clock not enabled\r\n");
        if (psram_status & PSRAM_ERR_INIT)
            printf ("  init register rejected\r\n");
        if (psram_status & PSRAM_ERR_TEST_PATTERN)
            printf ("  test pattern readback mismatch\r\n");
        if (psram_status & PSRAM_ERR_TEST_OFFSETS)
            printf ("  multi-offset test mismatch\r\n");
        if (psram_status & PSRAM_ERR_ROM_MIRROR)
            printf ("  hello_rom mirror mismatch (placeholder ROM?)\r\n");
        printf ("  cart stays on NONE (bus floats; check HCLK)\r\n");
    }

    /* MSX reset is no longer controlled by the cart - Init_Cart()
     * leaves PE4 floating so the MSX's own reset circuit handles it.
     * The MSX boots on its own and runs the cart handler whenever
     * ~SLTSL falls. */

    /* Main loop: idle (wfi) between CLI commands. The USART1 IRQ
     * assembles lines, CLI_Service() dispatches them here so response
     * printing never blocks RX. */
    for (;;) {
        CLI_Service();
        __asm__ volatile ("wfi");
    }
}