/* Autogenerated by hxtools bin2c */
#ifndef MSXTERM_H
#define MSXTERM_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_msxterm_bin[213];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* MSXTERM_H */
