#!/usr/bin/env python3
"""
rom2c.py - embed a raw MSX ROM image as the firmware's generated ROM source.

Usage:
    python3 rom2c.py <rom.bin> <output.c> [description]

Reads the ROM image (e.g. selector.bin, terminal.bin), emits a C file
whose symbol name is derived from the output filename and lives in the
.cartrom section (flash-resident), plus a matching _len symbol. The
ROM is embedded exactly as-is; the firmware's cart handler serves it
directly from flash at 0x4000..(0x4000 + rom_len).

ROM size is detected from the file, not hardcoded. selector.bin is a
full 32 KiB (the existing romloader.c fills the unused range with
real code + data). terminal.bin is small (~256 bytes) because the MSX
program only lives in 0x4000..0x40FF - bytes 0x4100..0xBFFF are never
fetched by the terminal code, so padding them wastes flash. Saves ~31
KiB on every rebuild.

Optional third argument is a short description that goes into the
generated header comment (default = "ROM cart image").

--nextor: Nextor kernel validation mode (docs/NEXTOR_PLAN.md D3):
  - 'AB' header at file offset 0 (bank 0 lives at Z80 0x4000);
  - size must be a multiple of 16384 (whole 16K banks);
  - "NEXTORv3_DRIVER" signature at <last bank>*16384 + 0x100;
  - the K_SIZE byte (0x40FE, = last bank's index) matches the bank count;
  - sha256 goes into the generated header comment.

Generated file is idempotent - rerunning after rebuilding the ROM just
updates the bytes and the embedded-pattern hash line.
"""

import hashlib
import os
import sys

PATTERN_OFF = 0x1000      # file offset of Z80 0x5000 in the .bin


def validate_nextor(rom: bytes, path: str) -> int:
    """Nextor ROM sanity checks; returns the driver bank index or exits."""
    if len(rom) % 16384 != 0:
        print(f"error: {path} size {len(rom)} is not a multiple of 16384",
              file=sys.stderr)
        sys.exit(1)
    nbanks = len(rom) // 16384
    k = nbanks - 1                     # driver bank = last bank
    if rom[0:2] != b"AB":
        print(f"error: {path} missing 'AB' header at file offset 0",
              file=sys.stderr)
        sys.exit(1)
    sig = rom[k * 16384 + 0x100:k * 16384 + 0x110]
    if not sig.startswith(b"NEXTORv3_DRIVER"):
        print(f"error: {path} missing NEXTORv3_DRIVER signature at "
              f"bank {k}+0x100 (got {sig.hex()})", file=sys.stderr)
        sys.exit(1)
    ksize = rom[k * 16384 + 0xFE]
    if ksize != k:
        print(f"error: {path} K_SIZE at bank {k}+0x40FE is {ksize}, "
              f"expected {k}", file=sys.stderr)
        sys.exit(1)
    return k


def main() -> int:
    args = sys.argv[1:]
    nextor_mode = "--nextor" in args
    args = [a for a in args if a != "--nextor"]
    if len(args) < 2 or len(args) > 3:
        print(f"usage: {sys.argv[0]} <rom.bin> <output.c> [description] "
              f"[--nextor]",
              file=sys.stderr)
        return 2

    rom_path, out_path = args[0], args[1]
    description = args[2] if len(args) >= 3 else "ROM cart image"

    with open(rom_path, "rb") as f:
        rom = f.read()
    rom_size = len(rom)
    if rom_size == 0:
        print(f"error: {rom_path} is empty", file=sys.stderr)
        return 1
    if rom[0:2] != b"AB":
        print(f"error: {rom_path} missing MSX ROM header 'AB' at 0x4000",
              file=sys.stderr)
        return 1

    extra = ""
    if nextor_mode:
        k = validate_nextor(rom, rom_path)
        extra = (f"\n * Nextor ROM (validated): {len(rom) // 16384} banks of "
                 f"16 KB, driver bank {k}\n")

    sha = hashlib.sha256(rom).hexdigest()
    rom_name = os.path.splitext(os.path.basename(out_path))[0]

    lines = []
    lines.append("/*")
    lines.append(f" * {rom_name}.c - embedded cart ROM image (AUTO-GENERATED "
                 "- do not edit).")
    lines.append(" *")
    lines.append(f" * Generated by tools/rom2c.py from {rom_path}")
    lines.append(f" *   sha256: {sha}")
    lines.append("\n".join(" * " + l if l else " *" for l in extra.split("\n"))
                 if extra else "")
    lines.append(" *")
    lines.append(f" * This is the {description} the MSX executes at boot.")
    lines.append(" * The ROM runs directly from flash and talks to the "
                 "firmware over the cart")
    lines.append(" * mailbox window (see cart.c) to drive the terminal UI.")
    lines.append(" *")
    lines.append(f" * Regenerate with:  python3 tools/rom2c.py "
                 f"{rom_path} {out_path} \"{description}\"")
    lines.append(" *")
    lines.append(" * Section notes:")
    lines.append(" *   - .cartrom keeps the image in FLASH (VMA==LMA, "
                 "KEEP()'d)")
    lines.append(" *     so the loader can boot like a normal ROM cartridge")
    lines.append(" *     while the LOADER mapper is installed.")
    lines.append(" */")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("__attribute__((section(\".cartrom\")))")
    lines.append(f"const uint8_t {rom_name}[{rom_size}] = {{")
    for i in range(0, rom_size, 8):
        chunk = rom[i:i + 8]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append(f"const uint32_t {rom_name}_len = {rom_size}U;")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"{out_path}: embedded {rom_size} bytes from {rom_path} "
          f"(sha256 {sha[:16]}...)")
    return 0


if __name__ == "__main__":
    sys.exit(main())