#!/usr/bin/env python3
"""
rom2c.py - embed a raw MSX ROM image as the firmware's generated ROM source.

Usage:
    python3 rom2c.py <rom.bin> <output.c>

Reads the 32 KiB ROM image (e.g. selector.bin), emits a C file whose
symbol name is derived from the output filename and lives in the
.cartrom section (flash-resident, 32 KiB), plus a matching _len symbol.
The ROM is embedded exactly as-is; the firmware's cart handler serves
it directly from flash at 0x4000..0xBFFF.

The firmware mirrors this array at boot into BOTH cart windows:
  - SRAM window: main() copies hello_rom[] -> s_cart_image_sram[]
  - PSRAM window: PSRAM_Init() copies + byte-verifies it @ 0x80000000

Generated file is idempotent - rerunning after rebuilding the ROM just
updates the bytes and the embedded-pattern hash line.
"""

import hashlib
import os
import sys

ROM_SIZE = 32768          # 32 KiB cart image
PATTERN_OFF = 0x1000      # file offset of Z80 0x5000 in the .bin


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <rom.bin> <output.c>", file=sys.stderr)
        return 2

    rom_path, out_path = sys.argv[1], sys.argv[2]

    with open(rom_path, "rb") as f:
        rom = f.read()
    if len(rom) != ROM_SIZE:
        print(f"error: {rom_path} is {len(rom)} bytes, expected {ROM_SIZE}",
              file=sys.stderr)
        return 1
    if rom[0:2] != b"AB":
        print(f"error: {rom_path} missing MSX ROM header 'AB' at 0x4000",
              file=sys.stderr)
        return 1

    sha = hashlib.sha256(rom).hexdigest()
    rom_name = os.path.splitext(os.path.basename(out_path))[0]

    lines = []
    lines.append("/*")
    lines.append(f" * {rom_name}.c - embedded cart ROM image (AUTO-GENERATED "
                 "- do not edit).")
    lines.append(" *")
    lines.append(f" * Generated by tools/rom2c.py from {rom_path}")
    lines.append(f" *   sha256: {sha}")
    lines.append(" *")
    lines.append(" * This is the 32 KiB ROM selector (MSXSoftware/RomLoader) "
                 "the MSX executes at boot.")
    lines.append(" * The loader runs directly from ROM and talks to the "
                 "firmware over the cart")
    lines.append(" * mailbox (see loader.h) to list USB .ROM files, load "
                 "one into PSRAM,")
    lines.append(" * pick a mapper and reset the MSX.")
    lines.append(" *")
    lines.append(" * Regenerate with:  make -C MSXSoftware/RomLoader embed")
    lines.append(" *")
    lines.append(" * Section notes:")
    lines.append(" *   - .cartrom keeps the image in FLASH (VMA==LMA, "
                 "KEEP()'d)")
    lines.append(" *     so the loader can boot like a normal ROM cartridge")
    lines.append(" *     while the LOADER mapper is installed.")
    lines.append(" */")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("__attribute__((section(\".cartrom\")))")
    lines.append(f"const uint8_t {rom_name}[{ROM_SIZE}] = {{")
    for i in range(0, ROM_SIZE, 8):
        chunk = rom[i:i + 8]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append(f"const uint32_t {rom_name}_len = {ROM_SIZE}U;")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"{out_path}: embedded {ROM_SIZE} bytes from {rom_path} "
          f"(sha256 {sha[:16]}...)")
    return 0


if __name__ == "__main__":
    sys.exit(main())